#!/bin/sh

ID_RSA=${ID_RSA:-/id_rsa}
_OPTS=" -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey -o ServerAliveInterval=60 -o ServerAliveCountMax=2"


if [ ! -f "$ID_RSA" ]; then
    ssh-keygen -q -P '' -f "$ID_RSA"
fi

while true; do
    ssh -T -i "$ID_RSA" $_OPTS $OPTS </dev/null
    if [ $? -eq 0 ]; then
        break
    fi
    date
    echo "=== todo: public key ==="
    ssh-keygen -y -f "$ID_RSA"
    sleep 10
done

echo "it's ok!"

exec ssh -t $_OPTS -i "$ID_RSA" \
    $_OPTS $OPTS \
	tmux new -A -s 0
